//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string RNC { get; set; }
        public string Telefono { get; set; }
        public string PersonaACargo { get; set; }
        public Nullable<int> CantidadEmpleados { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TipoComida { get; set; }
        public Nullable<double> VentasMensuales { get; set; }
        public string GuidReg { get; set; }
    }
}
