//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfRestaurant", Namespace="http://tempuri.org/", ItemName="restaurant")]
    [System.SerializableAttribute()]
    public class ArrayOfRestaurant : System.Collections.Generic.List<RestauranteApp.ServiceReference1.restaurant> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="restaurant", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class restaurant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonaACargoField;
        
        private System.Nullable<int> CantidadEmpleadosField;
        
        private System.Nullable<System.DateTime> FechaCreacionField;
        
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoComidaField;
        
        private System.Nullable<double> VentasMensualesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidRegField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RNC {
            get {
                return this.RNCField;
            }
            set {
                if ((object.ReferenceEquals(this.RNCField, value) != true)) {
                    this.RNCField = value;
                    this.RaisePropertyChanged("RNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PersonaACargo {
            get {
                return this.PersonaACargoField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaACargoField, value) != true)) {
                    this.PersonaACargoField = value;
                    this.RaisePropertyChanged("PersonaACargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> CantidadEmpleados {
            get {
                return this.CantidadEmpleadosField;
            }
            set {
                if ((this.CantidadEmpleadosField.Equals(value) != true)) {
                    this.CantidadEmpleadosField = value;
                    this.RaisePropertyChanged("CantidadEmpleados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TipoComida {
            get {
                return this.TipoComidaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoComidaField, value) != true)) {
                    this.TipoComidaField = value;
                    this.RaisePropertyChanged("TipoComida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<double> VentasMensuales {
            get {
                return this.VentasMensualesField;
            }
            set {
                if ((this.VentasMensualesField.Equals(value) != true)) {
                    this.VentasMensualesField = value;
                    this.RaisePropertyChanged("VentasMensuales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string GuidReg {
            get {
                return this.GuidRegField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidRegField, value) != true)) {
                    this.GuidRegField = value;
                    this.RaisePropertyChanged("GuidReg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceRestauranteSoap")]
    public interface WebServiceRestauranteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getAllRestaurantResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllRestaurant", ReplyAction="*")]
        RestauranteApp.ServiceReference1.getAllRestaurantResponse getAllRestaurant(RestauranteApp.ServiceReference1.getAllRestaurantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllRestaurant", ReplyAction="*")]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.getAllRestaurantResponse> getAllRestaurantAsync(RestauranteApp.ServiceReference1.getAllRestaurantRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getRestaurantResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRestaurant", ReplyAction="*")]
        RestauranteApp.ServiceReference1.getRestaurantResponse getRestaurant(RestauranteApp.ServiceReference1.getRestaurantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRestaurant", ReplyAction="*")]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.getRestaurantResponse> getRestaurantAsync(RestauranteApp.ServiceReference1.getRestaurantRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento deleteRestaurantResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteRestaurant", ReplyAction="*")]
        RestauranteApp.ServiceReference1.deleteRestaurantResponse deleteRestaurant(RestauranteApp.ServiceReference1.deleteRestaurantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteRestaurant", ReplyAction="*")]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.deleteRestaurantResponse> deleteRestaurantAsync(RestauranteApp.ServiceReference1.deleteRestaurantRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postRestaurant", ReplyAction="*")]
        RestauranteApp.ServiceReference1.postRestaurantResponse postRestaurant(RestauranteApp.ServiceReference1.postRestaurantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postRestaurant", ReplyAction="*")]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.postRestaurantResponse> postRestaurantAsync(RestauranteApp.ServiceReference1.postRestaurantRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/putRestaurant", ReplyAction="*")]
        RestauranteApp.ServiceReference1.putRestaurantResponse putRestaurant(RestauranteApp.ServiceReference1.putRestaurantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/putRestaurant", ReplyAction="*")]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.putRestaurantResponse> putRestaurantAsync(RestauranteApp.ServiceReference1.putRestaurantRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRestaurantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllRestaurant", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.getAllRestaurantRequestBody Body;
        
        public getAllRestaurantRequest() {
        }
        
        public getAllRestaurantRequest(RestauranteApp.ServiceReference1.getAllRestaurantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllRestaurantRequestBody {
        
        public getAllRestaurantRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRestaurantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllRestaurantResponse", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.getAllRestaurantResponseBody Body;
        
        public getAllRestaurantResponse() {
        }
        
        public getAllRestaurantResponse(RestauranteApp.ServiceReference1.getAllRestaurantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllRestaurantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RestauranteApp.ServiceReference1.ArrayOfRestaurant getAllRestaurantResult;
        
        public getAllRestaurantResponseBody() {
        }
        
        public getAllRestaurantResponseBody(RestauranteApp.ServiceReference1.ArrayOfRestaurant getAllRestaurantResult) {
            this.getAllRestaurantResult = getAllRestaurantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRestaurantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRestaurant", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.getRestaurantRequestBody Body;
        
        public getRestaurantRequest() {
        }
        
        public getRestaurantRequest(RestauranteApp.ServiceReference1.getRestaurantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRestaurantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getRestaurantRequestBody() {
        }
        
        public getRestaurantRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRestaurantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRestaurantResponse", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.getRestaurantResponseBody Body;
        
        public getRestaurantResponse() {
        }
        
        public getRestaurantResponse(RestauranteApp.ServiceReference1.getRestaurantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getRestaurantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RestauranteApp.ServiceReference1.restaurant getRestaurantResult;
        
        public getRestaurantResponseBody() {
        }
        
        public getRestaurantResponseBody(RestauranteApp.ServiceReference1.restaurant getRestaurantResult) {
            this.getRestaurantResult = getRestaurantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRestaurantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteRestaurant", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.deleteRestaurantRequestBody Body;
        
        public deleteRestaurantRequest() {
        }
        
        public deleteRestaurantRequest(RestauranteApp.ServiceReference1.deleteRestaurantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteRestaurantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public deleteRestaurantRequestBody() {
        }
        
        public deleteRestaurantRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRestaurantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteRestaurantResponse", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.deleteRestaurantResponseBody Body;
        
        public deleteRestaurantResponse() {
        }
        
        public deleteRestaurantResponse(RestauranteApp.ServiceReference1.deleteRestaurantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteRestaurantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteRestaurantResult;
        
        public deleteRestaurantResponseBody() {
        }
        
        public deleteRestaurantResponseBody(string deleteRestaurantResult) {
            this.deleteRestaurantResult = deleteRestaurantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postRestaurantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postRestaurant", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.postRestaurantRequestBody Body;
        
        public postRestaurantRequest() {
        }
        
        public postRestaurantRequest(RestauranteApp.ServiceReference1.postRestaurantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class postRestaurantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RNC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PersonaACargo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int CantidadEmpleados;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TipoComida;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public double VentasMensuales;
        
        public postRestaurantRequestBody() {
        }
        
        public postRestaurantRequestBody(string Nombre, string Direccion, string RNC, string Telefono, string PersonaACargo, int CantidadEmpleados, string TipoComida, double VentasMensuales) {
            this.Nombre = Nombre;
            this.Direccion = Direccion;
            this.RNC = RNC;
            this.Telefono = Telefono;
            this.PersonaACargo = PersonaACargo;
            this.CantidadEmpleados = CantidadEmpleados;
            this.TipoComida = TipoComida;
            this.VentasMensuales = VentasMensuales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postRestaurantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postRestaurantResponse", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.postRestaurantResponseBody Body;
        
        public postRestaurantResponse() {
        }
        
        public postRestaurantResponse(RestauranteApp.ServiceReference1.postRestaurantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class postRestaurantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string postRestaurantResult;
        
        public postRestaurantResponseBody() {
        }
        
        public postRestaurantResponseBody(string postRestaurantResult) {
            this.postRestaurantResult = postRestaurantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class putRestaurantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="putRestaurant", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.putRestaurantRequestBody Body;
        
        public putRestaurantRequest() {
        }
        
        public putRestaurantRequest(RestauranteApp.ServiceReference1.putRestaurantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class putRestaurantRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RNC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PersonaACargo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int CantidadEmpleados;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TipoComida;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double VentasMensuales;
        
        public putRestaurantRequestBody() {
        }
        
        public putRestaurantRequestBody(int id, string Nombre, string Direccion, string RNC, string Telefono, string PersonaACargo, int CantidadEmpleados, string TipoComida, double VentasMensuales) {
            this.id = id;
            this.Nombre = Nombre;
            this.Direccion = Direccion;
            this.RNC = RNC;
            this.Telefono = Telefono;
            this.PersonaACargo = PersonaACargo;
            this.CantidadEmpleados = CantidadEmpleados;
            this.TipoComida = TipoComida;
            this.VentasMensuales = VentasMensuales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class putRestaurantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="putRestaurantResponse", Namespace="http://tempuri.org/", Order=0)]
        public RestauranteApp.ServiceReference1.putRestaurantResponseBody Body;
        
        public putRestaurantResponse() {
        }
        
        public putRestaurantResponse(RestauranteApp.ServiceReference1.putRestaurantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class putRestaurantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string putRestaurantResult;
        
        public putRestaurantResponseBody() {
        }
        
        public putRestaurantResponseBody(string putRestaurantResult) {
            this.putRestaurantResult = putRestaurantResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceRestauranteSoapChannel : RestauranteApp.ServiceReference1.WebServiceRestauranteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceRestauranteSoapClient : System.ServiceModel.ClientBase<RestauranteApp.ServiceReference1.WebServiceRestauranteSoap>, RestauranteApp.ServiceReference1.WebServiceRestauranteSoap {
        
        public WebServiceRestauranteSoapClient() {
        }
        
        public WebServiceRestauranteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceRestauranteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceRestauranteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceRestauranteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestauranteApp.ServiceReference1.getAllRestaurantResponse RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.getAllRestaurant(RestauranteApp.ServiceReference1.getAllRestaurantRequest request) {
            return base.Channel.getAllRestaurant(request);
        }
        
        public RestauranteApp.ServiceReference1.ArrayOfRestaurant getAllRestaurant() {
            RestauranteApp.ServiceReference1.getAllRestaurantRequest inValue = new RestauranteApp.ServiceReference1.getAllRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.getAllRestaurantRequestBody();
            RestauranteApp.ServiceReference1.getAllRestaurantResponse retVal = ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).getAllRestaurant(inValue);
            return retVal.Body.getAllRestaurantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.getAllRestaurantResponse> RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.getAllRestaurantAsync(RestauranteApp.ServiceReference1.getAllRestaurantRequest request) {
            return base.Channel.getAllRestaurantAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.getAllRestaurantResponse> getAllRestaurantAsync() {
            RestauranteApp.ServiceReference1.getAllRestaurantRequest inValue = new RestauranteApp.ServiceReference1.getAllRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.getAllRestaurantRequestBody();
            return ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).getAllRestaurantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestauranteApp.ServiceReference1.getRestaurantResponse RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.getRestaurant(RestauranteApp.ServiceReference1.getRestaurantRequest request) {
            return base.Channel.getRestaurant(request);
        }
        
        public RestauranteApp.ServiceReference1.restaurant getRestaurant(int id) {
            RestauranteApp.ServiceReference1.getRestaurantRequest inValue = new RestauranteApp.ServiceReference1.getRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.getRestaurantRequestBody();
            inValue.Body.id = id;
            RestauranteApp.ServiceReference1.getRestaurantResponse retVal = ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).getRestaurant(inValue);
            return retVal.Body.getRestaurantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.getRestaurantResponse> RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.getRestaurantAsync(RestauranteApp.ServiceReference1.getRestaurantRequest request) {
            return base.Channel.getRestaurantAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.getRestaurantResponse> getRestaurantAsync(int id) {
            RestauranteApp.ServiceReference1.getRestaurantRequest inValue = new RestauranteApp.ServiceReference1.getRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.getRestaurantRequestBody();
            inValue.Body.id = id;
            return ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).getRestaurantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestauranteApp.ServiceReference1.deleteRestaurantResponse RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.deleteRestaurant(RestauranteApp.ServiceReference1.deleteRestaurantRequest request) {
            return base.Channel.deleteRestaurant(request);
        }
        
        public string deleteRestaurant(int id) {
            RestauranteApp.ServiceReference1.deleteRestaurantRequest inValue = new RestauranteApp.ServiceReference1.deleteRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.deleteRestaurantRequestBody();
            inValue.Body.id = id;
            RestauranteApp.ServiceReference1.deleteRestaurantResponse retVal = ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).deleteRestaurant(inValue);
            return retVal.Body.deleteRestaurantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.deleteRestaurantResponse> RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.deleteRestaurantAsync(RestauranteApp.ServiceReference1.deleteRestaurantRequest request) {
            return base.Channel.deleteRestaurantAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.deleteRestaurantResponse> deleteRestaurantAsync(int id) {
            RestauranteApp.ServiceReference1.deleteRestaurantRequest inValue = new RestauranteApp.ServiceReference1.deleteRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.deleteRestaurantRequestBody();
            inValue.Body.id = id;
            return ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).deleteRestaurantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestauranteApp.ServiceReference1.postRestaurantResponse RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.postRestaurant(RestauranteApp.ServiceReference1.postRestaurantRequest request) {
            return base.Channel.postRestaurant(request);
        }
        
        public string postRestaurant(string Nombre, string Direccion, string RNC, string Telefono, string PersonaACargo, int CantidadEmpleados, string TipoComida, double VentasMensuales) {
            RestauranteApp.ServiceReference1.postRestaurantRequest inValue = new RestauranteApp.ServiceReference1.postRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.postRestaurantRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Direccion = Direccion;
            inValue.Body.RNC = RNC;
            inValue.Body.Telefono = Telefono;
            inValue.Body.PersonaACargo = PersonaACargo;
            inValue.Body.CantidadEmpleados = CantidadEmpleados;
            inValue.Body.TipoComida = TipoComida;
            inValue.Body.VentasMensuales = VentasMensuales;
            RestauranteApp.ServiceReference1.postRestaurantResponse retVal = ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).postRestaurant(inValue);
            return retVal.Body.postRestaurantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.postRestaurantResponse> RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.postRestaurantAsync(RestauranteApp.ServiceReference1.postRestaurantRequest request) {
            return base.Channel.postRestaurantAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.postRestaurantResponse> postRestaurantAsync(string Nombre, string Direccion, string RNC, string Telefono, string PersonaACargo, int CantidadEmpleados, string TipoComida, double VentasMensuales) {
            RestauranteApp.ServiceReference1.postRestaurantRequest inValue = new RestauranteApp.ServiceReference1.postRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.postRestaurantRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Direccion = Direccion;
            inValue.Body.RNC = RNC;
            inValue.Body.Telefono = Telefono;
            inValue.Body.PersonaACargo = PersonaACargo;
            inValue.Body.CantidadEmpleados = CantidadEmpleados;
            inValue.Body.TipoComida = TipoComida;
            inValue.Body.VentasMensuales = VentasMensuales;
            return ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).postRestaurantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestauranteApp.ServiceReference1.putRestaurantResponse RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.putRestaurant(RestauranteApp.ServiceReference1.putRestaurantRequest request) {
            return base.Channel.putRestaurant(request);
        }
        
        public string putRestaurant(int id, string Nombre, string Direccion, string RNC, string Telefono, string PersonaACargo, int CantidadEmpleados, string TipoComida, double VentasMensuales) {
            RestauranteApp.ServiceReference1.putRestaurantRequest inValue = new RestauranteApp.ServiceReference1.putRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.putRestaurantRequestBody();
            inValue.Body.id = id;
            inValue.Body.Nombre = Nombre;
            inValue.Body.Direccion = Direccion;
            inValue.Body.RNC = RNC;
            inValue.Body.Telefono = Telefono;
            inValue.Body.PersonaACargo = PersonaACargo;
            inValue.Body.CantidadEmpleados = CantidadEmpleados;
            inValue.Body.TipoComida = TipoComida;
            inValue.Body.VentasMensuales = VentasMensuales;
            RestauranteApp.ServiceReference1.putRestaurantResponse retVal = ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).putRestaurant(inValue);
            return retVal.Body.putRestaurantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.putRestaurantResponse> RestauranteApp.ServiceReference1.WebServiceRestauranteSoap.putRestaurantAsync(RestauranteApp.ServiceReference1.putRestaurantRequest request) {
            return base.Channel.putRestaurantAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestauranteApp.ServiceReference1.putRestaurantResponse> putRestaurantAsync(int id, string Nombre, string Direccion, string RNC, string Telefono, string PersonaACargo, int CantidadEmpleados, string TipoComida, double VentasMensuales) {
            RestauranteApp.ServiceReference1.putRestaurantRequest inValue = new RestauranteApp.ServiceReference1.putRestaurantRequest();
            inValue.Body = new RestauranteApp.ServiceReference1.putRestaurantRequestBody();
            inValue.Body.id = id;
            inValue.Body.Nombre = Nombre;
            inValue.Body.Direccion = Direccion;
            inValue.Body.RNC = RNC;
            inValue.Body.Telefono = Telefono;
            inValue.Body.PersonaACargo = PersonaACargo;
            inValue.Body.CantidadEmpleados = CantidadEmpleados;
            inValue.Body.TipoComida = TipoComida;
            inValue.Body.VentasMensuales = VentasMensuales;
            return ((RestauranteApp.ServiceReference1.WebServiceRestauranteSoap)(this)).putRestaurantAsync(inValue);
        }
    }
}
